# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-10ec37b5-5e60-4e4f-8308-6d4ace6e4647";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-10ec37b5-5e60-4e4f-8308-6d4ace6e4647".device = "/dev/disk/by-uuid/10ec37b5-5e60-4e4f-8308-6d4ace6e4647";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6464-E361";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-fcfc36fc-6380-4f88-8181-1eba693087ca"; }
    ];

  boot.initrd.luks.devices."luks-fcfc36fc-6380-4f88-8181-1eba693087ca".device = "/dev/disk/by-uuid/fcfc36fc-6380-4f88-8181-1eba693087ca";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
